credentials:
  usernames:
    imashkin:
      email: ivan.mashkin2018@gmail.com
      name: Ivan Mashkin
      password: '$2b$12$Lk24wm5MEkiGQ0YaUs3Ud.HsEGX6hRJ0Zpg3Zr3MtXjqkP6Q1de5e'
    
    rleung:
      email: Ryan.Leung@fdmgroup.com
      name: Ryan Leung
      password: '$2b$12$g0kw8yxegBhJDIM6.dLppO2TkqIJ5zDYXXPW.S8kj782vEi6xLGXG'

    AM:
      email: Account.manager@fdmgroup.com
      name: Account Manager
      password: '$2b$12$QMe3W8B/NZhJ8MtUPqPWE..ha38q4IAkW3QCqKP0/7Qa6H5IFCM8W'

    

cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - ivan.mashkin2018@gmail.com